version: '3.7'
services:
  db:
    image: mongo:latest
    restart: always
    container_name: vdc_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27018:27017
    networks:
      - backend
  redis: 
    image: 'redis'
    container_name: 'redis_transporter'
    restart: always
    volumes:
      - ./redis:/data
    ports: 
      - '6479:6379'
    networks:
      - backend
  gateway:
    build:
      context: ./gateway
      target: development
    restart: always
    container_name: 'vdc_gateway'
    env_file:
      - .env
    hostname: gateway
    ports:
      - "8100:3000"
    networks:
      - backend
    command: npm run start:dev
    depends_on:
      - db
      - redis

  product:
    build:
      context: ./product
      target: development
    restart: always
    hostname: product
    container_name: 'vdc_product'
    env_file:
      - .env
    networks:
      - backend
    command: npm run start:dev
    depends_on:
      - db
      - redis
networks:
  backend:
    driver: bridge