version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    container_name: vdc_db
    environment:
      POSTGRES_USER: danhvt
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports: 
      - '25432:5432'
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data
  redis: 
    image: 'redis'
    container_name: 'redis_transporter'
    restart: always
    volumes:
      - ./redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports: 
      - '6479:6379'
    networks:
      - backend
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: vdc_gateway
    environment:
      - REDIS_HOST=redis://redis
    hostname: gateway
    ports:
      - "8100:3000"
    depends_on:
      - redis
    networks:
      - backend
  product:
    build:
      context: services/product
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: product
    container_name: vdc_product
    environment:
      - REDIS_HOST=redis://redis
      - DATABASE_URL=postgresql://danhvt:randompassword@db:5432/mydb?schema=public
    networks:
      - backend
    depends_on:
      - db
      - redis
volumes:
  postgres:
    name: vdc-pg
networks:
  backend:
    driver: bridge