version: '3.7'
services:
  product_db:
    image: postgres:12
    restart: always
    container_name: vdc_product_db
    environment:
      POSTGRES_USER: danhvt
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports: 
      - '25432:5432'
    volumes:
      - /tmp/product-db:/var/lib/postgresql/data
    networks:
      - backend
  tracking_db:
    image: 'bitnami/mongodb:latest'
    container_name: 'vdc_tracking_db'
    restart: always
    ports:
      - 28017:27017
    volumes:
      - /tmp/vdc_mongodb:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=randompassword
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=randompassword
      - MONGODB_DATABASE=my_db
    networks:
      - backend
  redis: 
    image: 'redis'
    container_name: 'vdc_redis'
    restart: always
    volumes:
      - /tmp/vdc_redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports: 
      - '6479:6379'
    networks:
      - backend
  gateway:
    image: node:14.15.4
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./gateway:/home/node/app
      - ./gateway/node_modules:/home/node/app/node_modules
    container_name: 'vdc_gateway'
    hostname: gateway
    ports:
      - "8100:3000"
    networks:
      - backend
    command: node_modules/.bin/nest start --watch
    depends_on:
      - product_db
      - redis

  product:
    image: node:14.15.4
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./services/product:/home/node/app
      - ./services/product/node_modules:/home/node/app/node_modules
    hostname: product
    container_name: 'vdc_product'
    networks:
      - backend
    command: node_modules/.bin/nest start --watch
    depends_on:
      - product_db
      - redis
  tracking:
    image: node:14.15.4
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./services/tracking:/home/node/app
      - ./services/tracking/node_modules:/home/node/app/node_modules
    hostname: tracking
    container_name: 'vdc_tracking'
    networks:
      - backend
    command: node_modules/.bin/nest start --watch
    depends_on:
      - tracking_db
      - redis
networks:
  backend:
    driver: bridge