version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    container_name: vdc_db
    environment:
      POSTGRES_USER: danhvt
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports: 
      - '25432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend
  redis: 
    image: 'redis'
    container_name: 'redis_transporter'
    restart: always
    volumes:
      - ./redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports: 
      - '6479:6379'
    networks:
      - backend
  gateway:
    image: node:14.15.4
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./gateway:/home/node/app
      - ./gateway/node_modules:/home/node/app/node_modules
    container_name: 'vdc_gateway'
    environment:
      - REDIS_HOST=redis://redis
    hostname: gateway
    ports:
      - "8100:3000"
    networks:
      - backend
    command: node_modules/.bin/nest start --watch
    depends_on:
      - db
      - redis

  product:
    image: node:14.15.4
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./product:/home/node/app
      - ./product/node_modules:/home/node/app/node_modules
    hostname: product
    container_name: 'vdc_product'
    environment:
      - REDIS_HOST=redis://redis
    networks:
      - backend
    command: node_modules/.bin/nest start --watch
    depends_on:
      - db
      - redis
networks:
  backend:
    driver: bridge